source 'https://rubygems.org'

# gem 'github-pages', group: :jekyll_plugins
gem 'kramdown-math-katex'
gem 'webrick'
gem 'logger'
gem 'csv'
gem 'bigdecimal'
gem 'base64'
gem 'ostruct'
gem 'wdm'
gem 'fiddle'
gem 'faraday-retry'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-highres-link'
